### ISSUE TITLE
Adding to comparisons

### ISSUE THREAD

**Issue by iandoug** [MadRabbit/halmak#1]
Hi

Mind if I add it here?
http://www.keyboard-design.com/best-ansi-layouts-as-determined-by-keyboard-layout-analyzer.html

Will help if you can send me the KLA .json file then I won't have to redo it and possibly get it wrong.. :-)

Thanks, Ian

**Comment by kaievns** [comment]
i see you've already done all the work :) awesome resource btw!

**Comment by iandoug** [comment]
Um, the version posted on this site is different to the previous two versions... is this Halmak 3 or does it replace both 1 and 2?

**Comment by kaievns** [comment]
i think that's a version 2.2. there were couple of more iterations on the Halmak 2 concept after it's official announcement :)

**Comment by iandoug** [comment]
Okay, am about to start (well, restart for the 3rd time) another cycle of tests, I'll add it to the mix. Should I keep Halmak 1 and 2 around or are they now redundant?

thanks, Ian

**Comment by kaievns** [comment]
Yeah, i think you can pretty much remove the old versions
