### ISSUE TITLE
Windows version now available

### ISSUE THREAD

**Issue by pguerin3** [MadRabbit/halmak#16]
https://github.com/pguerin3/halmak4windows

**Comment by kaievns** [comment]
ohey, do you mind making a PR for that please? thanks!

**Comment by pguerin3** [comment]
Check this out:
https://medium.com/@paulguerin/the-search-for-the-worlds-best-keyboard-layout-98d61b33b8e1?source=friends_link&sk=288b4ecba957175484463cfc7f1b6fe6

**Comment by kaievns** [comment]
nice write up, thanks! btw, halmak has the control underlay that keeps the ctrl, alt, win layers intact QWERTY like, so all your ctrl+ZXCV, S etc keep working the usual ;)

I have it working in OSX/Linux. I have a windows version as well laying around, just thought you might have it done better than I, since im not a real good window user ;)

**Comment by kaievns** [comment]
i can push mine in a PR if you want so you could compare notes and make it good. then i'd be happy to merge it, people had been asking for it for a while

**Comment by pguerin3** [comment]
I'm still a beginner in git, so if its easy from your end to merge then you can do that.

For the layers, my version remaps cntrl to follow Halmak, so undo/cut/copy/paste follows Halmak instead of Qwerty.
The alt and other layers follow Qwerty.
If this isn't what you want then I can change my version.

I also created an X11 version, that has the same behaviour as my Windows version (undo/cut/copy/paste follows Halmak)
I want to add it to the official repository: https://github.com/freedesktop/xkeyboard-config
Again if this isn't what you want then I can change my version.

You can advise on the direction you want to take.

**Comment by pguerin3** [comment]
Note - xkb is for the console terminal, and different to X11.
Most users will be using X11, so I considered the console version to be lower priority.
I did create a console version of Halmak.

**Comment by kaievns** [comment]
i have actually just published my linux configs https://github.com/MadRabbit/halmak/tree/master/linux it has the ctrl+zxcv working as QWERTY both in terminal and X11. using it right now :)

im mostly interested in the windows config at this point

**Comment by pguerin3** [comment]
I have been able to create a Halmak layout with the Qwerty cntrl keys.
The cntrl keys work like Qwerty - as expected in the gvim editor.
However when I use Chrome, Notepad, or Wordpad, the cntrl keys work like Halmak!
So this dual-personality is very unusual, and I don't have a workaround for this.

For me - I prefer the Halmak cntrl keys because I use the mouse to select, and copy, then the cntrl-v to paste.
In Halmak the v key is closer to the left cntrl - so less hand stretching - so much better than the Qwerty cntrl behaviour!

**Comment by pguerin3** [comment]
I just cracked the case!
I now have a Halmak layout with the Qwerty cntrl layout.
I'll update my repo soon.

**Comment by pguerin3** [comment]
I've updated: https://github.com/pguerin3/halmak4windows

Halmak maps to the Halmak layout for normal characters, and the Qwerty layout for control characters. This means undo (cntrl-z), cut (cntrl-x), copy (cntrl-c), and paste (cntrl-v) and the other control characters are in their original Qwerty positions on the keyboard.

HalmakX maps to the Halmak layout for both normal and control characters. This means undo (cntrl-z), cut (cntrl-x), copy (cntrl-c), and paste (cntrl-v) and the other control characters are in their new Halmak positions on the keyboard.

Tell me your thoughts so I can finalise for the pull request.

**Comment by kaievns** [comment]
hi there, closing this as there is no further actions
