### ISSUE TITLE
shift , and shift . on mac OSX produces ( and ) instead of < and >

### ISSUE THREAD

**Issue by testaccount1979** [MadRabbit/halmak#17]
hi, small bug .... on mac  OSX Catalina 10.15 shift comma and shift period have incorrect characters. ( Loving this over workman as  I am relearning touch typing 👍 )

**Comment by testaccount1979** [comment]
Hi, any update or way to remap the shift , or . command? all other characters work properly. minus the two central  which give the ( and ) , instead of mapped < > .

**Comment by dimaqq** [comment]
I imagine you only need to change these bits:

https://github.com/MadRabbit/halmak/blob/1c455ab9bc6a9a42127b3be0c654f46a9cfed033/macos/Halmak.bundle/Contents/Resources/Halmak.keylayout#L161-L162

https://github.com/MadRabbit/halmak/blob/1c455ab9bc6a9a42127b3be0c654f46a9cfed033/macos/Halmak.bundle/Contents/Resources/Halmak.keylayout#L182-L186

0x3e, 0x3c are `>` and `<`

**Comment by AndrewKvalheim** [comment]
Maybe it’s intentional? It does seem like a good idea. Confusing not to see it documented though.

**Comment by kaievns** [comment]
Hi folks, yes this is intentional, you type way more round braces than triangular, hence i had put them in the middle. closing, thanks
