### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by ylluminate** [MadRabbit/halmak#2]
So I found your analysis interesting and, frankly, I'd hope right on board if the last line of your features was true, "Has letters `ZXCV` and `S` in their original positions".  Unfortunately I'm seeing this in your layout image:

![example](https://cl.ly/1b3e193D250H/huh%3F.png)

Was this not compared to QWERTY as the baseline for the originals as noted in the readme?

**Comment by kaievns** [comment]
Hey :) so, the project moved on beyond that. now it has a completely reworked _typing_ layout, but it has the standard QWERTY _command_ layout.

in other words, when you just type text you use the new optimized for typing layout. but when you need to hit `ctrl+c`, `ctrl+v`, `ctrl+s`, etc. the layout flips into QWERTY mode, so you could retain all your muscle memory around those combinations. i hope that makes sense
