### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mulianov** [MadRabbit/halmak#3]
Could you please add Linux support?

**Comment by kaievns** [comment]
ohi, apologies for a super late response on this, didn't look in here in a while.

i wouldn't know how to, tbh :) but, if you make me one, i'd be happy to merge ;)

**Comment by kissu** [comment]
I'll maybe make it one day. 😁

**Comment by mirrorsonthewall** [comment]
I created something (that was tested in Ubuntu 19.10) if anyone would like to test it out and see if it works for them: https://github.com/mirrorsonthewall/halmaklinuxsupport

**Comment by kaievns** [comment]
ohi, i've just published my XKB configs. it supports the QWERTY controls (mostly), has mac ralt mode and works on ubuntu 20.04 https://github.com/MadRabbit/halmak/tree/master/linux
