### ISSUE TITLE
Opinion on symbols and numbers placement like programmer dvorak?

### ISSUE THREAD

**Issue by WTanardi** [MadRabbit/halmak#34]
I'm interested in your thoughts and opinion on revamping the numbers (and symbols) row, just like programmer dvorak, and if you would ever consider doing this? by either implementing it straight or in another alternate version.

Here's a picture of the programmer dvorak layout I took from wikipedia
![image](https://user-images.githubusercontent.com/90451337/142390686-f09d0d75-d67a-470b-9c3e-cc402858b5e2.png)

Ah, and also, would swapping the placement of backspace and caps-lock (Kinda like colemak) be of any use?

**Comment by dumblob** [comment]
Without running the GA myself I'm pretty certain this programmer's top row would score much lower than the one currently present in the current version of Halmak.

So, what is exactly your motivation of proposing this?

Btw. apart from "inefficient in the context of the rest of Halmak" the programmer's Dvorak doesn't even seem to win the "visually appealing design" match (it's not symmetric, it's not in any way "logical", ...).

So elaboration on your motivation would help here a lot to look at the idea from a different perspective which so far seems utterly shadowed to me.

**Comment by WTanardi** [comment]
There were no intrinsic motivation really, I was just curious, since halmak already moved basically every key I thought why not the number/symbols row too, because from what I read online, the people using prog. dvorak's number and symbols row has enjoyed it a lot, so I thought it would improve efficiency and whatnot.
Also, do you have an opinion on the caps-lock -- backspace swap? Acknowledging that everyone makes mistakes once in a while, I think having the backspace closer would add a huge benefit, since people rarely use the caps-lock anyways.

**Comment by dessalines** [comment]
I use capslock backspace, linux lets you do this easily with any layout, not requiring an actual modification. I also use halmak in vim, and its symbol and number placement work great. I don't think any changes are necessary.

**Comment by dumblob** [comment]
>Also, do you have an opinion on the caps-lock -- backspace swap? Acknowledging that everyone makes mistakes once in a while, I think having the backspace closer would add a huge benefit, since people rarely use the caps-lock anyways.

This is a very good question because from what I know, the GA's fitness function is built to "write text" and measure how far it gets with the given budget of "effort". But I'm not sure whether it can also delete text, so actually we probably can't tell how (in)efficient it is to have the backspace where it is. Technically there shouldn't be a reason to not remap backspace to some other key even on Windows. So this would IMHO require some more investigation.

To speak for myself, I'm using the classical *caps-lock <-> escape* swap to unfocus fields in UIs. I didn't experiment with repositioning *backspace* at all.

**Comment by WTanardi** [comment]
Ahh, great, thanks for the answers guys, I guess I'll be personalizing my own layout to test and see what's best for me
Btw, should I close this Issue? Or should I just leave it open?

**Comment by dumblob** [comment]
> Ahh, great, thanks for the answers guys, I guess I'll be personalizing my own layout to test and see what's best for me

You're welcome!

> Btw, should I close this Issue? Or should I just leave it open?

I'm in no position to decide but if you got all your answers, I'd probably close it :wink: (you can later open a new issue with your findings).

Btw. if you're going to fork this repo, let me know as I'd subscribe to your changes to the GA etc. to see your findings.

**Comment by WTanardi** [comment]
>Btw. if you're going to fork this repo, let me know as I'd subscribe to your changes to the GA etc. to see your findings.
Haha, I doubt I will do that, but I'll let you know if I do ! thanks a bunch !
