### ISSUE TITLE
Links to blog are broken

### ISSUE THREAD

**Issue by brettcannon** [MadRabbit/halmak#44]
E.g. http://nikolay.rocks/categories/optimal+keyboard is showing a Heroku error message (maybe because they shut down their free tier?).

**Comment by Zireael07** [comment]
Seconding. Wayback Machine failed e..g on the Prezo post.

**Comment by jurf** [comment]
They are available in markdown in the repo: https://github.com/kaievns/nikolay.rocks/tree/master/pages/Optimal%20Keyboard. Some images don't show up in the preview, so it might be better to read them directly from the source code.

**Comment by Chiramisudo** [comment]
For the record, here's an archive to the original article.

https://web.archive.org/web/20220818151548/https://nikolay.rocks/2016-12-20-the-halmak-reborn
