### ISSUE TITLE
Home row position is unnatural.

### ISSUE THREAD

**Issue by ghost** [MadRabbit/halmak#7]
Background: Typed on a colemak ergodone (ergodox clone) for a few years, and the 'laptop-style' keys layout is really different , but it is worth pointing out nevertheless, especially to those who are interested in *evolution*.

So here it is; the accepted home row position is forced. Try it now, just lay your fingers where they want to rest according to their length , youll find that either the middle and ring fingers go on the top row (ring finger is kinda between the two rows for me), or the little finger slides down one row (this is what the ergodone encourages my hand to do, since on a 'regular' keyboard, moving the left little finger down puts it halfway between 'z' and shift, and the keyboard already moves the middle columns up a bit). If you are interested to research this, Id like to develop a layout with this approach.

**Comment by kaievns** [comment]
that's inevitable, you're trying to use something that is designed with regular skewed keyboard efforts weighting system in mind, on an orto keyboard with keys vertically aligned, it's not going to be the best fit.

still probably better than QWERTY ;)

**Comment by ghost** [comment]
We have already swapped A with Z and 'O' with '/' on the ergodox. I have to admit that laptop keyboards hurt my wrist within minutes, so I avoid them. That being said, when I do use them, my lower pinky position is getting more annoying, so I might still create a layout eventually, as nixos makes it trivial for us to customize all our keyboards. Unsure if its possible to do this, but we would use the Lshift key as 'A when pressed, shift when held' , which is our current ergo setup. That way, the 'B' regular key can be used for something else (return?), and all the bottom rows can fell a lot more 'ergo' like.
