### ISSUE TITLE
Cmd+Key is not remapped on Mac in some apps

### ISSUE THREAD

**Issue by jwulf** [MadRabbit/halmak#9]
In Google Chrome, Command key combos are unmodified (using Halmak bundle).

In VS Code they are.

**Comment by kissu** [comment]
This is not a bug but intended. Check his video or blog for more details. :smile_cat:

**Comment by jwulf** [comment]
OK, I will modify it with Karabiner.

**Comment by jwulf** [comment]
I modified it in the layout itself in my fork.
